/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;
import clases.conectar;
import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.LocalDate;
import javax.swing.JOptionPane;


/**
 *
 * @author SEBASTIAN GOMEZ
 */
public class formulario extends javax.swing.JFrame {
    conectar conecto;
    
    PreparedStatement ps;
    ResultSet rs;
    
    private static Connection conn;
    private static final String driver = "com.mysql.jdbc.Driver";
    private static final String user = "root";
    private static final String pass = "";
    private static final String url = "jdbc:mysql://localhost:3306/licorerat";
    
    public formulario(){
        initComponents();
    }
    
    public Connection getConnection(){
        Connection conn=null;
        try {
            Class.forName(driver);
            conn = DriverManager.getConnection(url, user, pass);
            if(conn !=null) {
                System.out.println("La conexion se establecio bien con la DB");
            }
            
        } catch (ClassNotFoundException | SQLException e ) {
            System.out.println("Error al conectar con la DB" + e);
        }
        return conn;
    }
    
    public void Desconectar (){
        conn=null;
        if (conn == null) {
            System.out.println("Se desconecto la Db");
           
        }
    }    
    
    public void borrarCajas (){
        cajanombre.setText(null);
        cajanombrelicor.setText(null);
        cajaedad.setText(null);
        cajacedula.setText(null);
        
    }

    /**
     * Creates new form formulario
     */
  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cajanombre = new javax.swing.JTextField();
        cajanombrelicor = new javax.swing.JTextField();
        cajaedad = new javax.swing.JTextField();
        cajacedula = new javax.swing.JTextField();
        jconectar = new javax.swing.JButton();
        jdescconectar = new javax.swing.JButton();
        jenviar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jfondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nombre:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 64, 60, 20));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nombre Licor:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 94, 100, 20));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Edad:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 40, 20));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Cedula:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 50, 20));
        getContentPane().add(cajanombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 160, -1));
        getContentPane().add(cajanombrelicor, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 130, -1));
        getContentPane().add(cajaedad, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 180, -1));
        getContentPane().add(cajacedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 170, -1));

        jconectar.setText("conectar");
        jconectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jconectarActionPerformed(evt);
            }
        });
        getContentPane().add(jconectar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, -1, -1));

        jdescconectar.setText("desconectar");
        jdescconectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jdescconectarActionPerformed(evt);
            }
        });
        getContentPane().add(jdescconectar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, -1, -1));

        jenviar.setText("emviar");
        jenviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jenviarActionPerformed(evt);
            }
        });
        getContentPane().add(jenviar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 210, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Captura de pantalla 2020-11-27 125722_preview_rev_1.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 40, 140, 150));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel6.setText("LICORMAX");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 160, 50));

        jfondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/64663881-mesa-de-madera-y-vino-botella-de-licor-en-estante-fondo-borroso-se-puede-utilizar-para-la-visualizac.jpg"))); // NOI18N
        getContentPane().add(jfondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 280));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jconectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jconectarActionPerformed
        conecto = new conectar();
        Connection reg = conecto.getConnection();
    }//GEN-LAST:event_jconectarActionPerformed

    private void jdescconectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jdescconectarActionPerformed
        conecto.Desconectar();
    }//GEN-LAST:event_jdescconectarActionPerformed

    private void jenviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jenviarActionPerformed
        Connection conn = null;
        
        try {
            conn = getConnection();
            ps = conn.prepareStatement("INSERT INTO datos (nombre, nombrelicor, edad, Cedula, fechareg) VALUES(?,?,?,?,?)");
            ps.setString(1, cajanombre.getText());
            ps.setString(2, cajanombrelicor.getText());
            ps.setString(3, cajaedad.getText());
            ps.setString(4, cajacedula.getText());
            ps.setDate(5, Date.valueOf(LocalDate.now()));
            
            int result = ps.executeUpdate();
            if (result > 0) {
                JOptionPane.showMessageDialog(null, "Los datos fueron enviados correctamente");
                borrarCajas();
            }else{
                JOptionPane.showMessageDialog(null, "Los datos no fueron enviados");
            }
            conn.close();
            
            
        } catch (Exception e){
            System.out.println(e);
            
        }
                         
    }//GEN-LAST:event_jenviarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formulario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cajacedula;
    private javax.swing.JTextField cajaedad;
    private javax.swing.JTextField cajanombre;
    private javax.swing.JTextField cajanombrelicor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JButton jconectar;
    private javax.swing.JButton jdescconectar;
    private javax.swing.JButton jenviar;
    private javax.swing.JLabel jfondo;
    // End of variables declaration//GEN-END:variables
}
